## Lab_2a

### 1) Виконав приклади у файлі task.py

### 2)  Результат виконання команди python3 .
``````shell
We are in the __main__
2021-10-25 00:21:32.014378
linux
test
``````
### 3) Результат виконання команди  python3 . -h 
```shell
uusage: . [-h] [-o OPT] [-l]

Приклад передачі аргументів у Python програму.

optional arguments:
  -h, --help            show this help message and exit
  -o OPT, --optional OPT
                        Цей параметр є вибірковим.
  -l, --logs            Якщо виконати команду з цим параметром будуть
                        виводитись логи.

```
### 4) Параметр - python3 . -o "Цей текст також має вивестись"
```shell
We are in the __main__
2021-10-25 00:32:13.912039
linux
З консолі було передано аргумент
 ========== >> Цей текст також має вивестись << ==========
test

```
### 5)  python3 . --logs виводяться логи
```shell
2021-10-25 00:32:59,665 root INFO: Тут буде просто інформативне повідомлення
2021-10-25 00:32:59,666 root WARNING: Це Warning повідомлення
2021-10-25 00:32:59,666 root ERROR: Це повідомлення про помилку
test

```
### 6) Створив функцію, яка буде виводить всі парні числа до 100 
```shell
def EvenOdd(bool):
    for i in range(0,101):
        if(bool and i % 2 == 0):
            print(i)
        elif(not bool and i % 2 != 0):
            print(i)
```
### 7) Створив функцію яка може виконуватись з помилкою, в разі її винекнення ми зможено це побачити в логах
```shell
def error(x,y):
    try:
        a = x/y
        log.info("Програма виконалась")
        return a
    except Exception as ERROR:
        log.error("Помилка")
```
common.error(15,1)
```shell
2021-10-25 00:57:27,749 root INFO: Програма виконалась
```
### 8) Створив таблицю, та запустив пул-реквест